name: Buckyball CI (PR)
run-name: ${{ github.actor }} is running PR Test 🚀
on:
  pull_request:
    branches:
      - '*'

jobs:
  PR-Test:
    name: PR Test
    runs-on: cpu-server
    env:
      ALL_PROXY: socks5h://127.0.0.1:7890
    steps:
      - name: Print information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          echo "🔎 Branch: ${{ github.head_ref }} -> ${{ github.base_ref }}"
          echo "🔎 Repository: ${{ github.repository }}"

      # - uses: actions/checkout@v4
      # - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Reset to clean state
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          git fetch origin
          git clean -fd
          git checkout ${{ github.head_ref }}
          git pull
          git submodule update

      - name: Nix build
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix build

      - name: Build Workloads
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c bbdev workload --build

      - name: Build Verilator
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c bbdev verilator --clean
          nix develop -c bbdev verilator --verilog '--config sims.verilator.sims.verilator.BuckyballToyVerilatorConfig'
          nix develop -c bbdev verilator --build '--jobs 16'


      - run: echo "🍏 PR Test is ${{ job.status }}."
